name: release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set Environment Variables
              id: set-vars
              run: |
                  # Assume version-name is derived from apk-info action
                  tag_name="${{ steps.apk-info.outputs.version-name }}"
                  if [[ -z "$tag_name" ]]; then
                      echo "TAG_NAME is empty. Please check the source of the tag name."
                      exit 1
                  fi
                  echo "TAG_NAME=$tag_name" >> $GITHUB_ENV

            - name: Create Tag if Not Exists
              id: create-tag
              run: |
                  tag_name="${{ env.TAG_NAME }}"
                  if [[ -z "$tag_name" ]]; then
                      echo "TAG_NAME is not set. Exiting."
                      exit 1
                  fi

                  if ! git rev-parse "$tag_name" >/dev/null 2>&1; then
                      echo "Creating new tag: $tag_name"
                      git tag "$tag_name"
                      git push origin "$tag_name"
                  else
                      echo "Tag $tag_name already exists"
                  fi

            - name: Create Release
              if: env.APK_PATH != 'null' && env.TAG_NAME != 'null'
              uses: softprops/action-gh-release@v1
              with:
                  files: ${{ env.APK_PATH }}
                  tag_name: ${{ env.TAG_NAME }}
                  name: ${{ steps.apk-info.outputs.application-name }}
                  body: ${{ steps.apk-info.outputs.version-name }}
